#!/bin/sh
. /lib/functions/uci-defaults.sh
board_config_update
ucidef_set_interfaces_lan_wan "$(ip address | grep ^[0-9] | awk -F: '{print $2}' | grep -vE 'eth0|lo' | tr '\n' ' ')" "eth0"
board_config_flush
