#!/bin/sh
for p in $(ls /sys/class/net); do
    [ -e "/sys/class/net/$p/device" ] || continue
    case "$p" in
        lo|br-*|bat*|tun*|tap*|wg*|wwan*|rmnet*|p2p*|ifb*|teql*|gre*|erspan*|ip6tnl*|sit*|bond*|vlan*|eth0.*) continue ;;
    esac
    REAL="$REAL $p"
done
set -- $REAL
WAN="$1"; shift
LAN="$*"
uci -q delete network.lanb.ports
for p in $LAN; do uci add_list network.lanb.ports="$p"; done
uci commit network
/etc/init.d/network restart
