#!/bin/sh
i=0
while [ $i -lt 20 ]; do
    [ -n "$(uci show wireless 2>/dev/null | grep '=wifi-device')" ] && break
    wifi config; sleep 2; i=$((i+1))
done
for r in $(uci show wireless 2>/dev/null | grep '=wifi-device' | cut -d. -f2 | cut -d= -f1); do
    uci set wireless.$r.disabled='0'
    uci set wireless.$r.country='ID'
    uci set wireless.$r.htmode='HE80'
done
for s in $(uci show wireless 2>/dev/null | grep '=wifi-iface' | cut -d. -f2 | cut -d= -f1); do
    uci set wireless.$s.ssid='Masta Gohim'
    uci set wireless.$s.encryption='none'
    uci set wireless.$s.network='lan'
done
uci commit wireless
wifi reload
